### ISSUE TITLE
Server sent charset unknown to the client

### ISSUE THREAD

**Issue by rockenbach** [marcbria/docker4ojs#2]
Hi, @marcbria. Congratulations for your work here :)

I'm trying to setup a local instance of OJS on my machine but I'm always got the same error:

> Errors occurred during installation
> A database error has occurred: Server sent charset unknown to the client. Please, report to the developers

I followed your instructions on how to setup all database fields on the installation page and also selected 'Unicode (UTF-8)' on all charset fields. I'm also checked the `default_charset_set_name` of the ojs database and it is `utf8mb4`, so I really don't understand what is going wrong.

Please, can you help me to understand what I'm doing wrong?

**Comment by marcbria** [comment]
Hi Charles,

First at all, sorry for the lack of documentation.

"dojo" is an script to manage ojs-dockers, useful for those who like to create multiple instances of ojs, in different dockers.

I created this because I believe this architecture is much more flexible than the single instance model.

If you are still interested in running "dojo", change your branch to "experimental", because this code is still an undergoing project and "master" branch is deprecated... and then follow the installation instructions.


Otherwise, if you are only interested in running a OJS inside a docker (a single ojs can mange multiple journals), you can try with this:

https://github.com/marcbria/docker-pkp-ojs (that is and will be "dojo" compliant)

Or the original ojs-docker-compose project developed by Lucas Diedrich:

https://github.com/lucasdiedrich/ojs


Hope this helps,

m.


El 26/11/18 a las 15:13, Charles Rockenbach escribió:

Hi, @marcbria<https://github.com/marcbria>. Congratulations for your work here :)

I'm trying to setup a local instance of OJS on my machine but I'm always got the same error:

Errors occurred during installation
A database error has occurred: Server sent charset unknown to the client. Please, report to the developers

I followed your instructions on how to setup all database fields on the installation page and also selected 'Unicode (UTF-8)' on all charset fields. I'm also checked the default_charset_set_name of the ojs database and it is utf8mb4, so I really don't understand what is going wrong.

Please, can you help me to understand what I'm doing wrong?

**Comment by rockenbach** [comment]
In the end the problem were with the latest mysql' version that changed the default value of the `character_set_server` that was causing this issue (more info [here](https://github.com/docker-library/mysql/issues/284) and [here](https://dev.mysql.com/doc/relnotes/mysql/8.0/en/news-8-0-1.html#mysqld-8-0-1-charset)). As my goal was just setup an OJS version to see if it attends to my requirements, I just change de mysql' version to `mysql:5.7` and everything is working fine.

Thanks, @marcbria :+1:
